# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Container Scan
on: push
jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Check docker changes
      id: docker_changes
      run: git diff-tree --no-commit-id --name-only -r HEAD nginx tpl | wc -l | tr -d ' '

    - name: Build the Docker image
      if: steps.docker_changes.output != '0'
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest

    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      if: steps.docker_changes.output != '0'
      uses: anchore/scan-action@main
      with:
        image: "fabiocicerchia/nginx-lua:latest"
        acs-report-enable: true

    - name: Upload Anchore Scan Report
      if: steps.docker_changes.output != '0'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif